version: "2.4"
   
services:
  riddlr_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./riddlr.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    restart: always
    build: .
    #image: venkatvghub/foo-bar:latest
    #command: /app/start.sh
    #command: sleep 100000
    volumes:
      - .:/app
    links:
      - riddlr_db:riddlr_db
    environment:
      - DB_HOST=riddlr_db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    ports:
      - "8082:8082"
    depends_on:
      riddlr_db:
        condition: service_healthy


